# Imports

In [2]:
import numpy as np

# Code

In [3]:
x = np.linspace(0, 60, num=60, dtype=np.int64).reshape((5, 12))
print(x)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55 56 57 58 60]]


In [16]:
x[:, 1:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 60]])